<?php
/**
 * Live sitemap for Genie Media & Studio (Hostinger).
 *
 * .htaccess serves this at /sitemap.xml. It combines:
 *   - the site's fixed pages, taken from sitemap-pages.xml (generated by
 *     `npm run build` from src/app/sitemap.ts, so there is one list to edit);
 *   - every published blog post, fetched live from the backend API.
 * A post published in the admin panel appears here within CACHE_SECONDS,
 * with no rebuild.
 *
 * Resilience: the result is cached; if the backend is slow or down, the last
 * good sitemap (or the build-time one) is served instead of an error.
 *
 * __PLACEHOLDERS__ are filled from frontend-next/.env by scripts/postbuild.mjs.
 */

declare(strict_types=1);

const API_BASE_URL  = '__API_BASE_URL__';
const SITE_URL      = '__SITE_URL__';
const CACHE_SECONDS = 300;  // serve a cached copy for 5 minutes
const API_TIMEOUT   = 20;   // seconds; Render's free tier can be slow to wake

$pagesFile    = __DIR__ . '/sitemap-pages.xml';   // fixed pages (build time)
$fallbackFile = __DIR__ . '/sitemap-static.xml';  // full build-time sitemap
$cacheFile    = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'gm_sitemap_' . md5(__DIR__) . '.xml';

function send(string $xml): void
{
    header('Content-Type: application/xml; charset=utf-8');
    header('Cache-Control: public, max-age=' . CACHE_SECONDS);
    echo $xml;
    exit;
}

function fetchJson(string $url): ?array
{
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => API_TIMEOUT,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_HTTPHEADER     => ['Accept: application/json'],
            CURLOPT_FOLLOWLOCATION => true,
        ]);
        $body = curl_exec($ch);
        $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
    } else {
        $ctx = stream_context_create(['http' => ['timeout' => API_TIMEOUT, 'header' => "Accept: application/json\r\n"]]);
        $body = @file_get_contents($url, false, $ctx);
        $status = $body === false ? 0 : 200;
    }
    if ($body === false || $status !== 200) {
        return null;
    }
    $data = json_decode((string) $body, true);
    return is_array($data) ? $data : null;
}

function esc(string $value): string
{
    return htmlspecialchars($value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
}

/** Epoch milliseconds or a date string -> ISO 8601, or '' if unusable. */
function isoDate($value): string
{
    if ($value === null || $value === '') {
        return '';
    }
    if (is_numeric($value)) {
        $ts = (int) floor(((float) $value) / 1000);
    } else {
        $ts = strtotime((string) $value);
        if ($ts === false) {
            return '';
        }
    }
    return gmdate('Y-m-d\TH:i:s.000\Z', $ts);
}

/** "/blog/a/b/" -> "a/b" (permalinks are stored inconsistently in older rows). */
function cleanSlug(string $raw): string
{
    $s = preg_replace('#^/+#', '', $raw) ?? '';
    $s = preg_replace('#^blog/#', '', $s) ?? '';
    return preg_replace('#/+$#', '', $s) ?? '';
}

/** The post's canonical: its own URL, or an editor-set same-site /blog/ URL. */
function canonicalFor(array $blog): string
{
    $self = SITE_URL . '/blog/' . cleanSlug((string) ($blog['permalink'] ?? ''));
    $custom = trim((string) ($blog['canonical_url'] ?? ''));
    if ($custom === '' || !preg_match('#^https?://#i', $custom)) {
        return $self;
    }
    $parts = parse_url($custom);
    $site = parse_url(SITE_URL);
    $path = $parts['path'] ?? '/';
    if (($parts['host'] ?? '') === ($site['host'] ?? '') && strpos($path, '/blog/') === 0) {
        return rtrim($custom, '/');
    }
    return $self;
}

// 1. Fresh cache: serve it.
if (is_file($cacheFile) && time() - (int) filemtime($cacheFile) < CACHE_SECONDS) {
    send((string) file_get_contents($cacheFile));
}

// 2. Build from the fixed pages + live published posts.
$pages = is_file($pagesFile) ? (string) file_get_contents($pagesFile) : '';
$blogs = fetchJson(API_BASE_URL . '/api/blogs');

if ($pages !== '' && $blogs !== null) {
    $entries = [];
    foreach ($blogs as $blog) {
        if (!is_array($blog) || ($blog['status'] ?? '') !== 'published' || trim((string) ($blog['permalink'] ?? '')) === '') {
            continue;
        }
        // A post marked noindex must not be advertised.
        if (strpos((string) ($blog['robots_directive'] ?? ''), 'noindex') === 0) {
            continue;
        }
        $lastmod = isoDate($blog['last_modified_at'] ?? null) ?: isoDate($blog['updatedAt'] ?? null) ?: isoDate($blog['createdAt'] ?? null);
        $entry = "<url>\n<loc>" . esc(canonicalFor($blog)) . "</loc>\n";
        if ($lastmod !== '') {
            $entry .= "<lastmod>{$lastmod}</lastmod>\n";
        }
        $entry .= "<changefreq>weekly</changefreq>\n<priority>0.8</priority>\n";
        if (!empty($blog['image'])) {
            $entry .= "<image:image>\n<image:loc>" . esc((string) $blog['image']) . "</image:loc>\n</image:image>\n";
        }
        $entries[] = $entry . "</url>";
    }

    $xml = str_replace('</urlset>', implode("\n", $entries) . "\n</urlset>", $pages);
    @file_put_contents($cacheFile, $xml, LOCK_EX);
    send($xml);
}

// 3. Backend unavailable: last good copy, then the build-time sitemap.
if (is_file($cacheFile)) {
    send((string) file_get_contents($cacheFile));
}
if (is_file($fallbackFile)) {
    send((string) file_get_contents($fallbackFile));
}
http_response_code(503);
header('Retry-After: 300');
send('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>');
