<?php
/**
 * SEO bridge for the split deployment.
 *
 * THE PROBLEM THIS SOLVES
 * The public site is static files served by Hostinger at geniemedia.in. The API,
 * the database and everything that generates SEO output live on a separate Node
 * host. Crawlers only ever visit geniemedia.in, so a sitemap generated on the
 * API host is a sitemap nothing reads, and the server-injected <head> for
 * /blog/<slug> never reaches a bot.
 *
 * This file closes that gap. Apache maps the SEO paths here (see .htaccess) and
 * this fetches the generated response from the API host, caches it briefly on
 * disk, and serves it under the real domain.
 *
 * It is a bridge, not the implementation. Everything it serves is generated by
 * Backend/services/. When the site and the API are eventually served from the
 * same origin, delete the rewrite rules and this file becomes dead code.
 *
 * FAILURE BEHAVIOUR
 * If the API is unreachable, a stale cache entry is served in preference to an
 * error, and a static file in preference to nothing. A crawler that receives a
 * 500 for sitemap.xml may back off for days, so serving something slightly old
 * is always the better outcome.
 */

declare(strict_types=1);

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const API_BASE      = 'https://geniemedia.onrender.com';
const CACHE_DIR     = __DIR__ . '/.seo-cache';
const CACHE_TTL     = 900;   // 15 minutes for generated files
const BLOG_TTL      = 300;   // 5 minutes for rendered blog HTML
const FETCH_TIMEOUT = 8;     // seconds

// Paths this script is allowed to proxy, mapped to their content type.
// An explicit allow-list: the target URL is built from this table and never
// from user input, so a crafted request cannot turn this into an open proxy.
const ROUTES = [
    'sitemap.xml' => 'application/xml; charset=utf-8',
    'pages.xml'   => 'application/xml; charset=utf-8',
    'blogs.xml'   => 'application/xml; charset=utf-8',
    'robots.txt'  => 'text/plain; charset=utf-8',
    'llms.txt'    => 'text/plain; charset=utf-8',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function cache_path(string $key): string
{
    if (!is_dir(CACHE_DIR)) {
        @mkdir(CACHE_DIR, 0775, true);
    }
    return CACHE_DIR . '/' . sha1($key) . '.cache';
}

function cache_read(string $key, int $ttl): ?string
{
    $path = cache_path($key);
    if (!is_file($path)) {
        return null;
    }
    if (time() - filemtime($path) > $ttl) {
        return null;
    }
    $data = @file_get_contents($path);
    return $data === false ? null : $data;
}

/** Ignores the TTL. Used only when the upstream fetch has already failed. */
function cache_read_stale(string $key): ?string
{
    $path = cache_path($key);
    if (!is_file($path)) {
        return null;
    }
    $data = @file_get_contents($path);
    return $data === false ? null : $data;
}

function cache_write(string $key, string $value): void
{
    @file_put_contents(cache_path($key), $value, LOCK_EX);
}

/**
 * Fetches a URL, forwarding the caller's User-Agent.
 *
 * Forwarding matters: the backend logs whether a request came from a bot, and
 * stripping the agent here would make every crawler look like the same PHP
 * script. Returns null on any non-200 so the caller can fall back.
 */
function fetch_upstream(string $url): ?string
{
    $agent = $_SERVER['HTTP_USER_AGENT'] ?? 'GenieMedia-SEO-Proxy';

    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS      => 3,
            CURLOPT_TIMEOUT        => FETCH_TIMEOUT,
            CURLOPT_CONNECTTIMEOUT => 5,
            CURLOPT_USERAGENT      => $agent,
            CURLOPT_HTTPHEADER     => ['Accept: */*'],
        ]);
        $body   = curl_exec($ch);
        $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        return ($body !== false && $status === 200) ? (string) $body : null;
    }

    $context = stream_context_create([
        'http' => [
            'timeout'       => FETCH_TIMEOUT,
            'header'        => "User-Agent: {$agent}\r\nAccept: */*\r\n",
            'ignore_errors' => true,
        ],
    ]);

    $body = @file_get_contents($url, false, $context);
    if ($body === false) {
        return null;
    }

    $status = 0;
    foreach ($http_response_header ?? [] as $line) {
        if (preg_match('#^HTTP/\S+\s+(\d{3})#', $line, $m)) {
            $status = (int) $m[1];
        }
    }

    return $status === 200 ? $body : null;
}

function send(string $body, string $contentType, int $maxAge, string $source): void
{
    header('Content-Type: ' . $contentType);
    header('Cache-Control: public, max-age=' . $maxAge);
    header('X-SEO-Proxy: ' . $source);
    echo $body;
    exit;
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

$requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
$requestPath = '/' . ltrim($requestPath, '/');

// ---- Blog detail: /blog/<slug> --------------------------------------------
// The backend returns the full HTML document with <title>, the meta tags and
// the JSON-LD graph already injected into the head, plus the article text
// inside #root. That is what a crawler needs in the first response, without
// executing any JavaScript.
if (preg_match('#^/blog/(.+)$#', $requestPath, $m)) {
    $slug = trim($m[1], '/');

    // Only the shapes a real permalink can take. Rejecting everything else
    // keeps traversal and protocol tricks out of the upstream URL.
    if ($slug === '' || !preg_match('#^[A-Za-z0-9/_-]{1,200}$#', $slug) || strpos($slug, '..') !== false) {
        header('Location: /blogs', true, 302);
        exit;
    }

    $cacheKey = 'blog:' . $slug;

    if ($cached = cache_read($cacheKey, BLOG_TTL)) {
        send($cached, 'text/html; charset=utf-8', 60, 'hit');
    }

    $segments = array_map('rawurlencode', explode('/', $slug));
    $html     = fetch_upstream(API_BASE . '/blog/' . implode('/', $segments));

    if ($html !== null && $html !== '') {
        cache_write($cacheKey, $html);
        send($html, 'text/html; charset=utf-8', 60, 'miss');
    }

    if ($stale = cache_read_stale($cacheKey)) {
        send($stale, 'text/html; charset=utf-8', 60, 'stale');
    }

    // Last resort: the ordinary SPA shell. The post still renders for a human;
    // only the pre-rendered head is missing.
    $index = __DIR__ . '/index.html';
    if (is_file($index)) {
        send((string) file_get_contents($index), 'text/html; charset=utf-8', 0, 'fallback');
    }

    http_response_code(404);
    exit;
}

// ---- Generated site-wide files --------------------------------------------
$file = ltrim($requestPath, '/');

if (!isset(ROUTES[$file])) {
    http_response_code(404);
    exit;
}

$contentType = ROUTES[$file];
$cacheKey    = 'file:' . $file;

if ($cached = cache_read($cacheKey, CACHE_TTL)) {
    send($cached, $contentType, 3600, 'hit');
}

$body = fetch_upstream(API_BASE . '/' . $file);

if ($body !== null && trim($body) !== '') {
    cache_write($cacheKey, $body);
    send($body, $contentType, 3600, 'miss');
}

if ($stale = cache_read_stale($cacheKey)) {
    send($stale, $contentType, 600, 'stale');
}

// Static copies of robots.txt, pages.xml and services.xml are deployed with the
// build. Serving a slightly out-of-date one beats returning a 500, which some
// crawlers treat as a signal to stop asking for days.
$staticPath = __DIR__ . '/' . $file;
if (is_file($staticPath)) {
    send((string) file_get_contents($staticPath), $contentType, 600, 'static');
}

http_response_code(503);
header('Retry-After: 600');
